service: vf-coding-challenge

frameworkVersion: '2'
plugins:
    - serverless-s3-sync
    - invoke-push
    - serverless-iam-roles-per-function
custom:
  s3Sync:
    - bucketName: eltons-pokemon-bucket
      bucketPrefix: data 
      localDir: ./data 

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
    TABLE_NAME: PokemonTable
    BUCKET_NAME: eltons-pokemon-bucket
    DATA_KEY: data/Pokemon.csv

functions:
  pushToDynamo:
    handler: data-ingest.handle
    timeout: 30
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:ListBucket"
        Resource:
          Fn::GetAtt: [ PokemonBucket, Arn ]
      - Effect: "Allow"
        Action:
          - "s3:GetObject"
        Resource:
          Fn::Join: ['', [Fn::GetAtt: [ PokemonBucket, Arn ], '/*'] ]
      - Effect: Allow
        Action:
          - dynamodb:DescribeTable
          - dynamodb:BatchWriteItem
        Resource:
          - Fn::GetAtt: [ PokemonTable, Arn ]
          - Fn::Join: ['/', [Fn::GetAtt: [ PokemonTable, Arn ], 'index/*'] ]
  getTypesPokemon:
    handler: api/get-types.handle
    timeout: 30
    events:
      - http:
          path: get_pokemon_type/{type}
          method: get
          request:
            parameters:
              query:
                min_sum: true
              paths:
                type: true 
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
        Resource:
          - Fn::GetAtt: [ PokemonTable, Arn ]
          - Fn::Join: ['/', [Fn::GetAtt: [ PokemonTable, Arn ], 'index/*'] ]

resources:
  Resources:
    PokemonBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
    PokemonTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: Type
            AttributeType: S
          - AttributeName: Name
            AttributeType: S
          - AttributeName: StatSum
            AttributeType: N
        KeySchema:
          - AttributeName: Type
            KeyType: HASH
          - AttributeName: Name
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: StatIndex
            KeySchema: 
              - AttributeName: Type
                KeyType: HASH
              - AttributeName: StatSum
                KeyType: RANGE
            Projection: 
              ProjectionType: 'ALL'
        GlobalSecondaryIndexes:
          - IndexName: NameIndex
            KeySchema: 
              - AttributeName: Name
                KeyType: HASH
              - AttributeName: Type
                KeyType: RANGE
            Projection: 
              ProjectionType: 'ALL'
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1